- app/src/androidTest/java/com/escodro/alkaa/database/TaskDatabaseTest.kt
- app/src/androidTest/java/com/escodro/alkaa/framework/Checkers.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/CompletedTaskTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
- app/src/main/java/com/escodro/alkaa/common/extension/ViewExtensions.kt
- app/src/main/java/com/escodro/alkaa/data/local/dao/TaskDao.kt
- app/src/main/java/com/escodro/alkaa/ui/main/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListAdapter.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListContract.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/model/TaskEntry.kt
- app/src/main/res/layout/fragment_task_list.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
Create a separate list to contain all the completed tasks, this way the main screen does not is full of unused tasks after some usage.
> :sparkles: Move completed tasks to another list

- app/src/androidTest/java/com/escodro/alkaa/framework/AcceptanceTest.kt
- app/src/androidTest/java/com/escodro/alkaa/framework/rule/DisableAnimationsRule.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/CompletedTaskTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
Create rule to disable animation and remove/update the delays from test cases.
> Update delay from tests

- app/src/main/res/layout/fragment_category_list.xml
- app/src/main/res/navigation/nav_graph.xml
Update the fragment previews in Navigator graph
> :refactor: Update Navigator previews

- app/src/androidTest/java/com/escodro/alkaa/framework/Checkers.kt
- app/src/androidTest/java/com/escodro/alkaa/framework/Events.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_task_detail.xml
Update the layout and Manifest to make the Task description EditText
scrolls when the user is typing. Also added a ScrollView to enhance
the user experience, making the view grows as the user types.
> Fix unreachable text when too long due to keyboard

- app/build.gradle
Alkaa version from 1.0.1 to 1.1.0
> :bookmark: Update app version to 1.0.1

- .travis.yml
Version upgraded to Android 28
> :green_heart: Updating Travis CI Android version

- app/src/main/AndroidManifest.xml
Ops, I forgot it. The app must be portrait only.
> :lipstick: Force orientation to portrait

- app/src/main/res/anim/slide_enter_anim.xml
- app/src/main/res/anim/slide_exit_anim.xml
- app/src/main/res/anim/slide_pop_enter_anim.xml
- app/src/main/res/anim/slide_pop_exit_name.xml
Updating from 700ms to "config_longAnimTime" to match the Android
suggestions
> :lipstick: Update slide animation duration

- app/src/androidTest/java/com/escodro/alkaa/ui/NotificationTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/TaskReceiver.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/notification/TaskNotification.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/notification/TaskNotificationChannel.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/notification/TaskNotificationScheduler.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/ObservableWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskCompletedWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskNotifierWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskReschedulerWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskSnoozeWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailViewModel.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListViewModel.kt
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
Add "Done" and "Snooze" actions in Task Notifications to the user interact directly with it.
> Add Task notification actions

- app/build.gradle
Alkaa version from 1.1.0 to 1.2.0
> :bookmark: Update app version to 1.2.0

- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskCategoryContract.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskCategoryFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskCategoryViewModel.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailContract.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailProvider.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailViewModel.kt
- app/src/main/res/layout/fragment_task_detail.xml
- app/src/main/res/layout/fragment_task_detail_category.xml
Refactor Task Detail to break it in more classes, decreasing it code and complexity
> :recycle: Refactor Task Detail complexity

- app/build.gradle
- app/src/main/res/layout/fragment_task_detail.xml
Update Gradle to fail on Build warnings for better code maintainability
> :recycle: Update Gradle to fail on Build warnings

- app/build.gradle
- app/src/androidTest/java/com/escodro/alkaa/framework/extension/UiDeviceExtensions.kt
- app/src/main/java/com/escodro/alkaa/ui/about/AboutFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/notification/TaskNotification.kt
- build.gradle
- config/filters/detekt.yml
Libraries and quality checkers upgraded
New quality checkers errors fixed
> Update app dependencies

- app/build.gradle
Alkaa version from 1.2.0 to 1.2.1
> :bookmark: Update app version to 1.2.1

- app/src/androidTest/java/com/escodro/alkaa/framework/Checkers.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/MainDrawerTest.kt
- app/src/main/java/com/escodro/alkaa/common/extension/ViewExtensions.kt
- app/src/main/java/com/escodro/alkaa/common/extension/ViewGroupExtensions.kt
- app/src/main/java/com/escodro/alkaa/data/local/dao/CategoryDao.kt
- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/category/create/NewCategoryContract.kt
- app/src/main/java/com/escodro/alkaa/ui/category/create/NewCategoryFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/category/create/NewCategoryViewModel.kt
- app/src/main/java/com/escodro/alkaa/ui/category/detail/CategoryDetailContract.kt
- app/src/main/java/com/escodro/alkaa/ui/category/detail/CategoryDetailFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/category/detail/CategoryDetailViewModel.kt
- app/src/main/java/com/escodro/alkaa/ui/category/list/CategoryListFragment.kt
- app/src/main/res/layout/fragment_category_new.xml
- app/src/main/res/menu/category_menu.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
Create a feature to update the existing features, changing its name and color
> Add Update Category feature

- app/src/main/java/com/escodro/alkaa/ui/task/detail/main/TaskDetailFragment.kt
- app/src/main/res/navigation/nav_graph.xml
Update label structure to set empty String instead of using the SharedViewModel to reduce complexity
> :recycle: Refactor Navigation Graph empty label

- app/build.gradle
Alkaa version from 1.2.1 to 1.3.0
> Update app version to 1.3.0

- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/main/TaskDetailFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/main/TaskDetailViewModel.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListContract.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListViewModel.kt
Refactor the code smells and suggestion based on Vasiliy's review.
> Refactor the code based on Vasiliy Zukanov's review

- app/build.gradle
Alkaa version from 1.3.0 to 1.3.1
> :bookmark: Update app version to 1.3.1

- app/src/androidTest/java/com/escodro/alkaa/framework/AcceptanceTest.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/NotificationTest.kt
- app/src/main/java/com/escodro/alkaa/AlkaaApp.kt
- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/TaskReceiver.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/ObservableWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskCompletedWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskNotifierWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskReschedulerWorker.kt
- app/src/main/java/com/escodro/alkaa/ui/task/alarm/worker/TaskSnoozeWorker.kt
- build.gradle
> :arrow_up: Update Koin

- app/src/androidTest/java/com/escodro/alkaa/framework/rule/DisableAnimationsRule.kt
Now using the correct InstrumentationRegistry class
> :recycle: Update deprecated test import

- app/build.gradle
- build.gradle
- config/dependencies.gradle
- config/dependencies/android_dependencies.gradle
- config/dependencies/feature_dependencies.gradle
- config/quality/detekt.gradle
- config/quality/ktlint.gradle
Create base Gradle files to be reused in several modules. This allows to reuse libraries, versions and SDK matching in all modules.
> Manage dependencies to be reused in several modules 

- app/src/main/AndroidManifest.xml
At the moment, once the UI is not final, the multi-window support is
being removed
> :fire: Removing Multi-Window support (for now)

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.3.1 to 1.3.2
> :bookmark: Update app to version 1.3.2

- buildSrc/src/main/java/Dependencies.kt
- config/filters/detekt.yml
- features/alarm/build.gradle
- features/alarm/src/test/java/com/escodro/alarm/TaskNotificationSchedulerTest.kt
- libraries/core/src/main/java/com/escodro/core/extension/ContextExtensions.kt
> Create initial Unit Tests in Alarm module

- app/build.gradle
- buildSrc/src/main/java/Dependencies.kt
- features/alarm/build.gradle
- gradle.properties
- libraries/core/build.gradle
Just the ol' good clean up and minor refactor
> :recycle: General code clean up

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.3.2 to 1.3.3
> :bookmark: Update app to version 1.3.3

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.3.3 to 1.4.0
> :bookmark: Update app to version 1.4.0

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.4.0 to 1.4.2
Version updated due to some wrong updates on Google Play.
> :bookmark: Update app to version 1.4.2

- libraries/splitInstall/src/main/res/values-pt-rBR/strings.xml
- libraries/splitInstall/src/main/res/values/strings.xml
String updated informing the user that installing it over some network
conditions may cause additional charges
> Update Split Install disclaimer

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.4.2 to 1.4.3
> :bookmark: Update app to version 1.4.3

- .travis.yml
Config file updated to remove unneeded commands
> :construction_worker: Update Travis CI config file

- README.md
Update README adding links about Dynamic Delivery and linking to new Travis CI badge
> :pencil: Update README

- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- features/alarm/src/main/java/com/escodro/alarm/di/AlarmModule.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/tracker/src/main/java/com/escodro/tracker/di/TrackerModule.kt
Update all classes that does not need to retain state from `single` to
`factory`
Closes #71
> :recycle: Update all Mappers and Use Case injections to Factory

- .travis.yml
- buildSrc/src/main/java/Dependencies.kt
- data/local/src/main/java/com/escodro/local/converter/DateConverter.kt
- data/local/src/main/java/com/escodro/local/di/LocalModule.kt
- features/alarm/src/main/java/com/escodro/alarm/di/AlarmModule.kt
- features/category/src/main/java/com/escodro/category/di/CategoryModule.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListFragment.kt
- features/tracker/src/main/java/com/escodro/tracker/di/TrackerModule.kt
- features/tracker/src/main/java/com/escodro/tracker/presentation/TrackerViewModel.kt
- libraries/core/src/main/java/com/escodro/core/di/CoreModule.kt
Updating main Alkaa dependencies
> Upgrade dependencies

- app/src/androidTest/java/com/escodro/alkaa/database/TaskDatabaseTest.kt
- data/domain/src/main/java/com/escodro/domain/repository/TaskWithCategoryRepository.kt
- data/domain/src/main/java/com/escodro/domain/usecase/task/GetFutureTasks.kt
- data/domain/src/main/java/com/escodro/domain/usecase/task/SnoozeTask.kt
- data/domain/src/main/java/com/escodro/domain/usecase/taskwithcategory/LoadCompletedTasks.kt
- data/domain/src/main/java/com/escodro/domain/usecase/taskwithcategory/LoadUncompletedTasks.kt
- data/domain/src/main/java/com/escodro/domain/usecase/tracker/LoadCompletedTasksByPeriod.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/DeleteCategoryTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/LoadAllCategoriesTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/LoadCategoryTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/AddTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/DeleteTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/GetFutureTasksTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/GetTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/SnoozeTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/UpdateTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/taskwithcategory/LoadCompletedTasksTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/taskwithcategory/LoadUncompletedTasksTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/tracker/LoadCompletedTasksByPeriodTest.kt
- data/local/src/main/java/com/escodro/local/dao/TaskWithCategoryDao.kt
- data/local/src/main/java/com/escodro/local/datasource/TaskWithCategoryLocalDataSource.kt
- data/repository/src/main/java/com/escodro/repository/TaskWithCategoryRepositoryImpl.kt
- data/repository/src/main/java/com/escodro/repository/datasource/TaskWithCategoryDataSource.kt
- features/alarm/src/test/java/com/escodro/alarm/TaskNotificationSchedulerTest.kt
Once the Domain is the most important layer on Alkaa, adding more tests will make it more reliable and easy to refactor.
> Add more tests for Domain layer

- app/src/androidTest/java/com/escodro/alkaa/ui/NotificationTest.kt
Today the `Alarm` module is too much coupled with the UI modules. An idea is to make it more like a library than a companion module.
**EDIT**: After analyzing better the code, yes, the code is a little to coupled with Task logic. However, at the moment there is no alarm/notification expected for any other feature. If I refactor this code, it will only be for organization but creating abstractions for using in one class. To review this issue after new FDN features implemented.
Closes #70
> Refactor Alarm module

- libraries/core/src/main/java/com/escodro/core/extension/ViewExtensions.kt
The Material library is freaking crazy. Suppress wrong warning for now.
> Fix broken CI

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.4.3 to 1.5.0
> Update app to version 1.5.0

- app/src/androidTest/java/com/escodro/alkaa/ui/NotificationTest.kt
> Update Instrumented Tests

- README.md
Adding CodeFactor as auxiliary Quality Tool
> Add CodeFactor

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.5.0 to 1.6.0
> Alkaa version updated to 1.6.0

- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
- features/task/src/main/java/com/escodro/task/presentation/list/model/TaskEntry.kt
- features/task/src/main/res/layout/item_task.xml
Add new icon on the task list to better inform the user
> Update UI to show repeating icon

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.6.0 to 1.6.1
> Alkaa version updated to 1.6.1

- buildSrc/src/main/java/Dependencies.kt
Alkaa version updated from 1.6.1 to 1.7.0
> :bookmark: Alkaa version updated to 1.7.0

- .github/workflows/android.yml
- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
Create a GitHub Action to run Instrumented Tests
> Create Action to run Connected Tests

- app/src/androidTest/java/com/escodro/alkaa/ui/CategoryFlowTest.kt
> :white_check_mark: Update flaky tests

- .github/workflows/android.yml
- .travis.yml
- buildSrc/src/main/java/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
Due to new Gradle Plugin requirements, we need to updated it to JDK 11.
> Fix CI issues

- app/build.gradle
- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskItemTest.kt
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- app/src/main/java/com/escodro/alkaa/presentation/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- buildSrc/src/main/java/Dependencies.kt
- features/task/build.gradle
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailState.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListViewState.kt
- features/task/src/main/res/values-pt-rBR/strings.xml
- features/task/src/main/res/values/strings.xml
- features/task/src/test/java/com/escodro/task/presentation/list/TaskListViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/list/fake/LoadUncompletedTasksFake.kt
- features/task/src/test/java/com/escodro/task/presentation/list/fake/TaskFake.kt
- features/task/src/test/java/com/escodro/task/presentation/list/fake/UpdateTaskStatusFake.kt
- libraries/core/src/main/java/com/escodro/core/coroutines/CoroutineDebouncer.kt
The basic flow list>detail was created for the main screen of the application, the task list.
Several changes will be required, but for now, this is it!
> Create the basic flow for List/Detail in Tasks

- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/repository/CategoryRepository.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/LoadAllCategories.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/implementation/LoadAllCategoriesImpl.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/AddCategoryTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/fake/CategoryRepositoryFake.kt
- data/local/src/main/java/com/escodro/local/dao/CategoryDao.kt
- data/local/src/main/java/com/escodro/local/datasource/CategoryLocalDataSource.kt
- data/repository/src/main/java/com/escodro/repository/CategoryRepositoryImpl.kt
- data/repository/src/main/java/com/escodro/repository/datasource/CategoryDataSource.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailComponents.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailState.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailViewModel.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskDetailViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/LoadAllCategoriesFake.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/LoadUncompletedTasksFake.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/TaskFake.kt
- features/task/src/test/java/com/escodro/task/presentation/list/TaskListViewModelTest.kt
- libraries/theme/src/main/java/com/escodro/theme/Shape.kt
Add the category selection chips in the Task Detail screen in order to allow the user to moce the task between them.
> Add Category selection in Task Detail

- config/filters/detekt.yml
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailComponents.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- features/task/src/main/res/values-pt-rBR/strings.xml
- features/task/src/main/res/values/strings.xml
Simple components positions updated and strings updated.
> Minor changes in Task Detail

- gradle.properties
Bye, bye Jetfier.
Hello faster builds.
> Remove Jetfier from the project

- .github/workflows/android.yml
- app/build.gradle
- app/src/androidTest/java/com/escodro/alkaa/TaskItemTest.kt
- buildSrc/src/main/java/Dependencies.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- gradle/wrapper/gradle-wrapper.properties
> Fix the Continuous Integration

- app/build.gradle
- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- config/dependencies/compose_dependencies.gradle
- features/task/build.gradle
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskDetailTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskItemTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskListTest.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailComponents.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- libraries/test/build.gradle
- libraries/test/src/main/java/com/escodro/test/Assertions.kt
- libraries/test/src/main/java/com/escodro/test/Filters.kt
Now that the pipeline is running fine again, let's create more tests!
> Update and create more instrumented tests

- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- buildSrc/src/main/java/Dependencies.kt
- features/task/build.gradle
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskDetailTest.kt
- features/task/src/androidTest/java/com/escodro/task/espresso/Events.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailActions.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/TaskAlarmViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/category/CategorySelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/category/TaskCategoryState.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/category/TaskCategoryViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetailState.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetailViewModel.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskAlarmViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskCategoryViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskDetailViewModelTest.kt
Some refactors found during the coding like better packaging and add flaky behavior in some tests that mixes Jetpack Compose and Android View System.
Special thanks for @JoseAlcerreca for helping me with repeat/flaky tests in Compose.
> Task Detail refactors

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- buildSrc/src/main/java/Dependencies.kt
- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/repository/SearchRepository.kt
- data/domain/src/main/java/com/escodro/domain/usecase/search/SearchTasksByName.kt
- data/domain/src/main/java/com/escodro/domain/usecase/search/implementation/SearchTasksByNameImpl.kt
- data/domain/src/test/java/com/escodro/domain/usecase/fake/SearchRepositoryFake.kt
- data/domain/src/test/java/com/escodro/domain/usecase/search/SearchTasksTest.kt
- data/local/src/main/java/com/escodro/local/dao/TaskWithCategoryDao.kt
- data/local/src/main/java/com/escodro/local/datasource/SearchLocalDataSource.kt
- data/local/src/test/java/com/escodro/local/datasource/SearchLocalDataSourceTest.kt
- data/repository/src/main/java/com/escodro/repository/SearchRepositoryImpl.kt
- data/repository/src/main/java/com/escodro/repository/datasource/SearchDataSource.kt
- features/search/build.gradle
- features/search/src/androidTest/java/com/escodro/search/SearchSectionTest.kt
- features/search/src/main/java/com/escodro/search/di/SearchModule.kt
- features/search/src/main/java/com/escodro/search/mapper/TaskSearchMapper.kt
- features/search/src/main/java/com/escodro/search/model/TaskSearchItem.kt
- features/search/src/main/java/com/escodro/search/presentation/Search.kt
- features/search/src/main/java/com/escodro/search/presentation/SearchUIState.kt
- features/search/src/main/java/com/escodro/search/presentation/SearchViewModel.kt
- features/search/src/main/java/com/escodro/search/presentation/SearchViewState.kt
- features/search/src/main/res/values-pt-rBR/strings.xml
- features/search/src/main/res/values/strings.xml
- features/search/src/test/java/com/escodro/search/fake/SearchTaskByNameFake.kt
- features/search/src/test/java/com/escodro/search/presentation/SearchViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskDetailViewModelTest.kt
- gradle/wrapper/gradle-wrapper.properties
Implement the feature to search the exiting tasks on Alkaa
> Implement the Task Search feature

- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/HomeActions.kt
- features/preference/build.gradle
- features/preference/src/androidTest/java/com/escodro/preference/AboutTest.kt
- features/preference/src/androidTest/java/com/escodro/preference/PreferenceSectionTest.kt
- features/preference/src/main/java/com/escodro/preference/presentation/About.kt
- features/preference/src/main/java/com/escodro/preference/presentation/Preference.kt
- features/preference/src/main/res/values-pt-rBR/strings.xml
- features/preference/src/main/res/values/strings.xml
Now it is time to implement the most ~irrelevant~ simple flow in the project: the preferences!
> Implement Preference screen

- app/build.gradle
- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- app/src/main/java/com/escodro/alkaa/presentation/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- buildSrc/src/main/java/Dependencies.kt
- config/dependencies/compose_dependencies.gradle
- features/preference/src/main/java/com/escodro/preference/presentation/About.kt
- features/preference/src/main/java/com/escodro/preference/presentation/Preference.kt
- features/search/src/main/java/com/escodro/search/presentation/Search.kt
- features/task/build.gradle
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskItemTest.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/category/CategorySelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- libraries/theme/build.gradle
- libraries/theme/src/main/java/com/escodro/theme/components/AlkaaComponents.kt
- libraries/theme/src/main/java/com/escodro/theme/temp/getViewModel.kt
Update Compose and Kotlin to latest dependencies and make the CI pass again!
> Update compose to latest dependency

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/usecase/task/AddTask.kt
- data/domain/src/main/java/com/escodro/domain/usecase/task/implementation/AddTaskImpl.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/CancelAlarmTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/RescheduleFutureAlarmsTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/ScheduleAlarmTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/ScheduleNextAlarmTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/ShowAlarmTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/UpdateTaskAsRepeatingTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/AddTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/CompleteTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/DeleteTaskTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/task/UpdateTaskTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskListTest.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
- features/task/src/main/java/com/escodro/task/presentation/add/AddTaskViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- features/task/src/main/res/values-pt-rBR/strings.xml
- features/task/src/main/res/values/strings.xml
- features/task/src/test/java/com/escodro/task/presentation/add/AddTaskViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/AddTaskFake.kt
Implement the feature to finally add tasks via application! 😊
> Implement Add Task feature

- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- features/preference/src/main/java/com/escodro/preference/presentation/About.kt
- features/preference/src/main/res/values-pt-rBR/strings.xml
- features/preference/src/main/res/values/strings.xml
- features/search/src/main/java/com/escodro/search/presentation/Search.kt
- features/search/src/main/java/com/escodro/search/presentation/SearchViewState.kt
- features/task/src/androidTest/java/com/escodro/task/TaskListTest.kt
- features/task/src/main/java/com/escodro/task/presentation/category/CategorySelection.kt
- features/task/src/main/java/com/escodro/task/presentation/category/CategoryState.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailActions.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetailState.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListViewState.kt
- libraries/theme/src/main/java/com/escodro/theme/components/AlkaaComponents.kt
- libraries/theme/src/main/res/values-pt-rBR/strings.xml
- libraries/theme/src/main/res/values/strings.xml
Implement some changes needed to give the app a better UI and UX.
> Update minor UI changes

- buildSrc/src/main/java/Dependencies.kt
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
Update Compose and related libraries to latest versions and re-enable the tests that were failing in beta-01.
> Update Compose to latest beta

- features/task/src/androidTest/java/com/escodro/task/TaskListTest.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskStateHandler.kt
Refactored the BottomSheet in order to make it more generic and avoiding
passing states around once that hoisting it is better.
> ♻️ Refactor Task List BottomSheet

- data/domain/src/main/java/com/escodro/domain/model/Category.kt
- data/local/schemas/com.escodro.local.TaskDatabase/4.json
- data/local/src/androidTest/java/com/escodro/local/MigrationTest.kt
- data/local/src/main/java/com/escodro/local/TaskDatabase.kt
- data/local/src/main/java/com/escodro/local/migration/Migration.kt
- data/local/src/main/java/com/escodro/local/model/Category.kt
- data/local/src/main/java/com/escodro/local/provider/DatabaseProvider.kt
- data/repository/src/main/java/com/escodro/repository/model/Category.kt
- features/category-api/src/main/java/com/escodro/categoryapi/model/Category.kt
- features/category/src/main/java/com/escodro/category/presentation/CategorySection.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- features/task/src/main/java/com/escodro/task/presentation/category/CategorySelection.kt
This was a decision that I made in the beginning of the project which is impacting the design. There are no possibility for the user create a Category with null fields, so this should be not possible.
> Refactor Category table to remove nullable values

- buildSrc/src/main/java/Dependencies.kt
Android Gradle Plugin updated to reflect the lastes Android Studio
version
> ⬆️ Upgrade AGP to latest version

- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/DeleteCategory.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/implementation/DeleteCategoryImpl.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/DeleteCategoryTest.kt
- features/category/src/main/java/com/escodro/category/di/CategoryModule.kt
- features/category/src/main/java/com/escodro/category/presentation/CategoryBottomSheet.kt
- features/category/src/main/java/com/escodro/category/presentation/CategoryEditViewModel.kt
- features/category/src/main/res/values-pt-rBR/strings.xml
- features/category/src/main/res/values/strings.xml
- features/category/src/test/java/com/escodro/category/fake/DeleteCategoryFake.kt
- features/category/src/test/java/com/escodro/category/presentation/CategoryEditViewModelTest.kt
- libraries/theme/src/main/java/com/escodro/theme/components/AlkaaDialogs.kt
Implement the feature to let user remove created categories.
> Implement remove category feature

- buildSrc/src/main/java/Dependencies.kt
Android Gradle Plugin updated to match latest Android Studio canary
version
> ⬆️ Upgrade Android Gradle Plugin

- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/res/values-pt-rBR/strings.xml
- features/task/src/main/res/values/strings.xml
Implement a simple Snackbar to be shown when the user completes the
task. It informs which task was completed and give the ability to undo
the action, making the tasks return to the list.
> ✨ Implement "Undo Snackbar" for Task completion

- app/src/main/java/com/escodro/alkaa/model/HomeSection.kt
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
- buildSrc/src/main/java/Dependencies.kt
- config/dependencies/compose_dependencies.gradle
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
Some icons and components updated for a better look and feel. Probably more updates will be needed in the future, but at the moment, this is it!
> General UI updates

- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- buildSrc/src/main/java/Dependencies.kt
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
All Compose deps were updated to latest
> ⬆️ Upgrade all Compose-related dependencies

- features/category/src/main/java/com/escodro/category/presentation/CategorySection.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
Now the lists of Task and Category have a better organization when in
landscape.
> 💄 Update lists for better landscape support

- features/category/src/main/java/com/escodro/category/presentation/CategorySection.kt
Expression to calculate the number of columns updated to show at least
2 columns.
> 💄 Update Category Section to show at least 2 columns

- app/src/main/res/values-night/bools.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/bools.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- features/task/src/main/java/com/escodro/task/presentation/category/CategorySelection.kt
General updates in order to a better look and feel, specially in dark
theme
> 💄 General UI updates for dark theme

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/category/src/main/java/com/escodro/category/di/CategoryModule.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryAddViewModel.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryBottomSheetState.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryColors.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryEditViewModel.kt
- features/category/src/main/java/com/escodro/category/presentation/list/CategoryList.kt
- features/category/src/main/java/com/escodro/category/presentation/list/CategoryListViewModelImpl.kt
- features/category/src/test/java/com/escodro/category/presentation/bottomsheet/CategoryAddViewModelTest.kt
- features/category/src/test/java/com/escodro/category/presentation/bottomsheet/CategoryEditViewModelTest.kt
- features/category/src/test/java/com/escodro/category/presentation/list/CategoryListViewModelTest.kt
Files updated in more packages in order to better separate the concerns
and make the code easier to navigate.
> 🚚 Organize Category presentation files

- features/category/src/main/java/com/escodro/category/presentation/list/CategoryList.kt
Remove the placeholder and add a more appropriate asset.
> 🍱 Update Category item asset

- buildSrc/src/main/java/Dependencies.kt
The first beta of Alkaa 2.0 with Jetpack Compose is released!
> 🔖 Release Alkaa 2.0.0-beta01

- buildSrc/src/main/java/Dependencies.kt
- features/tracker/src/main/java/com/escodro/tracker/presentation/TrackerActivity.kt
- libraries/splitInstall/src/main/java/com/escodro/splitinstall/SplitInstall.kt
Library updated due to Google Play requirement.
Minor changes made to match latest library.
> ⬆️ Upgrade Google Play Core library

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/category/src/main/res/values-pt-rBR/strings.xml
- features/category/src/main/res/values/strings.xml
- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
- libraries/designsystem/src/main/java/com/escodro/designsystem/components/AlkaaComponents.kt
Minor beta changes for the user interface and experience
> Update UI and UX

- features/preference/src/main/java/com/escodro/preference/presentation/About.kt
- libraries/designsystem/src/main/java/com/escodro/designsystem/Color.kt
The classic color animation in About screen is back!
(I hope someone will actually see it...)
> 💄 Add the About header animation

- buildSrc/src/main/java/Dependencies.kt
The first beta of Alkaa 2.0 with Jetpack Compose is released!
> 🔖 Release Alkaa 2.0.0-beta02

- buildSrc/src/main/java/Dependencies.kt
Compose version updated to 1.0.0-alpha06
> ⬆️ Update Compose to latest beta

- buildSrc/src/main/java/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
In order to match latest Android Studio Bumblebee, the dependencies were
updated!
> ⬆️ Upgrade Gradle-related dependencies to latest version

- app/src/main/java/com/escodro/alkaa/AlkaaApp.kt
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- buildSrc/src/main/java/Dependencies.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- libraries/test/src/main/java/com/escodro/test/Filters.kt
Now we are in Compose 1.0.0-beta09!
> ⬆️ Upgrade dependencies to latest Compose

- buildSrc/src/main/java/Dependencies.kt
The third beta of Alkaa 2.0 with Jetpack Compose is released!
>  🔖 Release Alkaa 2.0.0-beta03

- buildSrc/src/main/java/Dependencies.kt
The stable version of Alkaa 2.0.0 is among us! ❤️
> 🔖 Release Alkaa 2.0.0 final

- buildSrc/src/main/java/Dependencies.kt
Gradle updated to latest alpha version
> ⬆️ Upgrade dependencies to latest Gradle

- .github/workflows/android_tests.yml
- buildSrc/src/main/java/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
I'm so happy to upgrade Alkaa to Jetpack Compose after all this great
support from the community!
> ⬆️ Upgrade to Compose 1.0 stable!

- buildSrc/build.gradle.kts
Gradle version updated to match latest Android Studio version
> ⬆️ Upgrade Gradle version

- features/preference/src/main/java/com/escodro/preference/presentation/Preference.kt
New Easter Egg added whe clicking multiple times in the "Version" item
in the "More" section. By the code, it seems that it opens an YouTube
link... I wonder which video is shown...
> 🥚 Add a new Easter Egg

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/AlkaaApp.kt
- buildSrc/src/main/java/Dependencies.kt
- buildSrc/src/main/java/gradle/android-library.gradle.kts
- buildSrc/src/main/java/gradle/dynamic-feature.gradle.kts
- domain/build.gradle.kts
[root-cause] Debug logs are not working properly
[solution] Add a fork of slf4j which correctly handles Android debug
logs to work together with Kotlin Logging library
> 🐞 Fix Log issues

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- buildSrc/src/main/java/Dependencies.kt
Now the transition between the Home and the Task Detail has a animation
to slide in and out, similar to Alkaa 1.0.
The library Accompanist was added to add this support.
> 💫 Add Transition Animation between screens

- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
Well, I forgot to update it before merging...
> ✏️ Fix minor typo

- buildSrc/src/main/java/Dependencies.kt
Update the version from 2.0.2 to 2.0.3
>  🔖 Release Alkaa 2.0.3

- buildSrc/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Build Gradle version updated to latest version matching Android Studio
Canary
> ⬆️ Upgrade Build Gradle version

- .github/workflows/build.yml
- domain/src/main/java/com/escodro/domain/usecase/alarm/RescheduleFutureAlarms.kt
- domain/src/main/java/com/escodro/domain/usecase/alarm/ScheduleNextAlarm.kt
- domain/src/main/java/com/escodro/domain/usecase/alarm/ShowAlarm.kt
- domain/src/main/java/com/escodro/domain/usecase/alarm/SnoozeAlarm.kt
- domain/src/main/java/com/escodro/domain/usecase/alarm/implementation/UpdateTaskAsRepeatingImpl.kt
- domain/src/main/java/com/escodro/domain/usecase/category/implementation/AddCategoryImpl.kt
- domain/src/main/java/com/escodro/domain/usecase/task/DeleteTask.kt
- domain/src/main/java/com/escodro/domain/usecase/task/implementation/AddTaskImpl.kt
Well, here we are again with some problems regarding Unit Tests.
> Fix Unit Tests

- buildSrc/src/main/java/Dependencies.kt
Update the version from 2.0.3 to 2.1.0
> 🔖 Release Alkaa 2.1.0

- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- libraries/test/build.gradle.kts
Upgrade from 1.0.3 to 1.2.0-rc03
> ⬆️ Update Jetpack Compose version

- buildSrc/src/main/java/Dependencies.kt
Update the version from 2.1.1 to 2.1.2
>  🔖 Release Alkaa 2.1.2

- app/build.gradle.kts
- features/category/src/main/java/com/escodro/category/presentation/list/CategoryList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/tracker/build.gradle.kts
- gradle/libs.versions.toml
- plugins/src/main/java/AlkaaVersions.kt
Update Compose and related libraries to use the latest Compose 1.2.1.
> Update compose to v1.2.1

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- plugins/src/main/java/AlkaaVersions.kt
Update from version 2.1.2 to 2.1.3
> 🔖 Release Alkaa 2.1.3

- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Adding support for Themed Icons on Android 13 allowing Alkaa to have the same system look and feel.
> 🍱 Support Themed Icons on Android 13

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.0

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/HomeActions.kt
- build.gradle.kts
- features/preference/build.gradle.kts
- features/preference/src/androidTest/java/com/escodro/preference/PreferenceSectionTest.kt
- features/preference/src/androidTest/java/com/escodro/preference/ThemePreferenceTest.kt
- features/preference/src/main/java/com/escodro/preference/presentation/OpenSource.kt
- features/preference/src/main/java/com/escodro/preference/presentation/Preference.kt
- features/preference/src/main/java/com/escodro/preference/presentation/PreferenceItem.kt
- features/preference/src/main/res/values-pt-rBR/strings.xml
- features/preference/src/main/res/values/strings.xml
- gradle/libs.versions.toml
- libraries/navigation/src/main/java/com/escodro/navigation/Destinations.kt
Recently, I found a great library that provides open-source licenses for all the project dependencies.
Thank you @mikepenz and all the contributors of https://github.com/mikepenz/AboutLibraries.
> Add open source licenses screen

- app/src/main/java/com/escodro/alkaa/di/AppModule.kt
- data/datastore/src/main/java/com/escodro/datastore/di/DataStoreModule.kt
- data/local/src/main/java/com/escodro/local/di/LocalModule.kt
- data/repository/src/main/java/com/escodro/repository/di/RepositoryModule.kt
- domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- features/alarm/src/main/java/com/escodro/alarm/di/AlarmModule.kt
- features/category/src/main/java/com/escodro/category/di/CategoryModule.kt
- features/glance/src/main/java/com/escodro/glance/di/GlanceModule.kt
- features/preference/src/main/java/com/escodro/preference/di/PreferenceModule.kt
- features/search/src/main/java/com/escodro/search/di/SearchModule.kt
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- libraries/core/src/main/java/com/escodro/core/di/CoreModule.kt
Recently, I found out that is possible to use class constructor instead of manual instantiation. No more `get(), get(), get(), get()...`.
> ♻️ Move the Koin injections to use class constructor

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.1

- gradle/libs.versions.toml
Update Compose version, which needs to update Kotlin version, which needs to update Accompanist too.
> ⬆️ Update Compose version

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/category/src/main/java/com/escodro/category/presentation/list/CategoryList.kt
- features/preference/src/main/java/com/escodro/preference/presentation/AppThemeDialog.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
Since the Material Design 3 is stable, some APIs are also stable.
> 🔥 Remove unused @OptIn values

- .github/workflows/generate_tag.yml
That would make my life easier to generate releases. :)
> 👷 Implement a GitHub action to create tags

- .github/workflows/generate_tag.yml
The GitHub Actions is broken. Let's try to fix it!
> 👷 Update broken GitHub actions

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.2

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/AlkaaApp.kt
- app/src/test/java/com/escodro/alkaa/KoinInjectionTest.kt
Add a new test to validate that all injections are well defined in the application.
> ✅ Add Dependency Injection test

- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.3

- app/build.gradle.kts
- build.gradle.kts
- data/datastore/build.gradle.kts
- data/local/build.gradle.kts
- data/local/src/main/java/com/escodro/local/di/LocalModule.kt
- domain/build.gradle.kts
- features/alarm/build.gradle.kts
- features/category-api/build.gradle.kts
- features/glance/build.gradle.kts
- features/preference/build.gradle.kts
- features/search/build.gradle.kts
- features/task/build.gradle.kts
- features/task/src/main/java/com/escodro/task/presentation/category/CategorySelection.kt
- gradle/libs.versions.toml
- libraries/core/build.gradle.kts
- libraries/designsystem/build.gradle.kts
- libraries/splitInstall/build.gradle.kts
- libraries/test/build.gradle.kts
A new plugin was added to help find unused and transitive dependencies. Thanks for the amazing library and community support, @autonomousapps.
> Add Dependency Analysis plugin

- domain/src/main/java/com/escodro/domain/di/DomainModule.kt
Although the injections were working, they were simply horrible. During the Koin refactor, I messed up with some of them since I use some auto replace.
> ♻️ Refactor some wrong injections

- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.4

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.5

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- data/repository/build.gradle.kts
- domain/build.gradle.kts
- features/alarm/proguard-rules.pro
- features/glance/proguard-rules.pro
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
> 💚 Remove all build warnings

- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.6

- .github/workflows/android_tests.yml
- README.md
> 🔧 Update the Android Tests in CI based on Now In Android

- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.2.7

- app/build.gradle.kts
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/tracker/build.gradle.kts
- libraries/test/build.gradle.kts
- plugins/src/main/java/extension/CommonExtension.kt
Fix the `packagingOptions` and `textFieldColors` deprecations
> 🚨 Fix build warnings

- .github/workflows/android_tests.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
> Revert "👷 Setup GitHub Actions cache for Gradle"

- plugins/src/main/java/AlkaaVersions.kt
> 🔖 Release Alkaa 2.3.0

- .github/workflows/release.yml
The environment variables were updated in the `build` and not in the `release` yml. Now it should be fine.
> 👷 Fix Release CI

- .github/workflows/build.yml
New `build-ios` job created to ensure that the iOS app keeps running in the future changes
> 👷 Add iOS build in GitHub Actions

- app/src/main/java/com/escodro/alkaa/MainActivity.kt
- features/category/src/commonMain/kotlin/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/list/TaskList.kt
- resources/src/commonMain/resources/MR/base/strings.xml
- resources/src/commonMain/resources/MR/pt-br/strings.xml
- shared/src/androidMain/kotlin/com/escodro/shared/Main.android.kt
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
- shared/src/commonMain/kotlin/com/escodro/shared/navigation/AlkaaNavGraph.kt
Small UI and usability polishes. ✨
> 🌟 Small polishes

- shared/build.gradle.kts
- shared/src/androidMain/kotlin/com/escodro/shared/di/PlatformSharedModule.kt
- shared/src/commonMain/kotlin/com/escodro/shared/di/SharedModule.kt
- shared/src/iosMain/kotlin/com/escodro/shared/di/PlatformSharedModule.kt
The Glance feature was enabled only for Android. Very simple code-wise.
> ✨ Re-enable Glance feature for Android

- features/home/build.gradle.kts
- features/home/src/commonMain/kotlin/com/escodro/home/navigation/HomeScreen.kt
- features/home/src/commonMain/kotlin/com/escodro/home/presentation/HomeScreen.kt
- gradle/libs.versions.toml
- libraries/appstate/build.gradle.kts
- libraries/appstate/src/commonMain/kotlin/com/alkaa/appstate/AlkaaAppState.kt
- libraries/appstate/src/commonMain/kotlin/com/escodro/appstate/AlkaaAppState.kt
- settings.gradle.kts
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
- shared/src/commonMain/kotlin/com/escodro/shared/navigation/AlkaaNavGraph.kt
Bringing back WindowSizeClass to Alkaa KMP thanks to @chrisbanes's library.
> 🪟 Re-enable WindowSizeClass to support multiple screen sizes

- assets/whatsnew/whatsnew-en-US
- assets/whatsnew/whatsnew-pt-BR
- gradle/libs.versions.toml
- ios-app/alkaa/Info.plist
> 🔖 Release Alkaa 3.0.0

- gradle/libs.versions.toml
> 🔖 Release Alkaa 3.0.2

- ios-app/alkaa/Info.plist
Added more API descriptions used by third-party libraries.
> 👷 Add API descriptions

- gradle/libs.versions.toml
- ios-app/PrivacyInfo.xcprivacy
- ios-app/alkaa.xcodeproj/project.pbxproj
- ios-app/alkaa.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios-app/alkaa/Info.plist
> 🔖 Release Alkaa 3.0.3

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖 Release Alkaa 3.0.5

- features/category/src/commonMain/kotlin/com/escodro/category/navigation/CategoryBottomSheet.kt
- features/glance/proguard-rules.pro
- features/home/src/commonMain/kotlin/com/escodro/home/navigation/HomeScreen.kt
- features/preference/src/commonMain/kotlin/com/escodro/preference/navigation/AboutScreen.kt
- features/preference/src/commonMain/kotlin/com/escodro/preference/navigation/OpenSourceScreen.kt
- features/preference/src/commonMain/kotlin/com/escodro/preference/navigation/TrackerScreen.kt
- features/task/src/commonMain/kotlin/com/escodro/task/navigation/AddTaskBottomSheet.kt
- features/task/src/commonMain/kotlin/com/escodro/task/navigation/TaskDetailScreen.kt
- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
- libraries/splitInstall/proguard-rules.pro
- plugins/src/main/java/com.escodro.android-compose.gradle.kts
- plugins/src/main/java/com.escodro.android-dynamic.gradle.kts
- plugins/src/main/java/com.escodro.multiplatform.gradle.kts
The last release is working fine on iOS but breaking on Android.
> 🚨 Fix 3.0.5 Android issues

- gradle.properties
Lately the CI is failing due to memory issues. Have 6 Gb then.
> 🧠 Increase Java Heap Size

- gradle/libs.versions.toml
> 2️⃣ Update Kotlin to 2.0.0

- app/src/main/java/com/escodro/alkaa/MainActivity.kt
- data/datastore/build.gradle.kts
- data/local/build.gradle.kts
- data/repository/build.gradle.kts
- domain/build.gradle.kts
- features/alarm/build.gradle.kts
- features/category-api/build.gradle.kts
- features/category/build.gradle.kts
- features/home/build.gradle.kts
- features/preference/build.gradle.kts
- features/search/build.gradle.kts
- features/task/build.gradle.kts
- features/tracker/build.gradle.kts
- libraries/appstate/build.gradle.kts
- libraries/coroutines/build.gradle.kts
- libraries/designsystem/build.gradle.kts
- libraries/di/build.gradle.kts
- libraries/navigation/build.gradle.kts
- libraries/test/build.gradle.kts
- plugins/src/main/java/com.escodro.android-dynamic.gradle.kts
- plugins/src/main/java/extension/KmpExtensions.kt
- resources/build.gradle.kts
- shared/build.gradle.kts
The extensions from `KmpExtensions` were replaced by the new additions in the latest KMP plugin.
> 📽️ Update Kotlin DSL with new extensions

- app/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> ⬆️ Update AGP to the latest version

- gradle/libs.versions.toml
All Koin dependencies were updated to v4.0.0
> ⬆️ Update Koin dependencies

- gradle/libs.versions.toml
Upgrading Android SDK Compile and Target versions
> 🤖 Update Android SDK

- features/task/src/commonMain/kotlin/com/escodro/task/presentation/add/TaskBottomSheet.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/compose/saver/LocalDateTimeSaver.kt
- gradle/libs.versions.toml
Compose Compiler updated to the latest version
> 🏈 Update Compose Compiler

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖 Release Alkaa 3.0.8

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖Release Alkaa 3.0.9

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖 Release Alkaa 3.1.0

- gradle/libs.versions.toml
- shared/src/iosMain/kotlin/com/escodro/shared/Main.ios.kt
> 🐚 Update to Compose 1.8.0-alpha03

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖 Release Alkaa 3.2.0

- resources/src/commonMain/composeResources/values/strings.xml
Corrected minor needless escapes, string template and updated the description of the application in the About screen to highlight multiplatform support.
Fixes: #862
> 💬 Update strings resources

- gradle/libs.versions.toml
> 🤖 Update Android Gradle Plugin

- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
> 🔖 Release Alkaa 3.3.0

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/escodro/alkaa/MainActivity.kt
- shared/src/androidMain/kotlin/com/escodro/shared/Main.android.kt
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
The following improvements are proposed:
- Improve and simplify Navigation Bar color
- Enable Predictive Back Gesture
> 🖼️ Minor UI improvements

- domain/build.gradle.kts
- features/alarm/build.gradle.kts
- gradle/libs.versions.toml
- resources/src/commonMain/composeResources/files/aboutlibraries.json
The library was unused and the dependency was creating all sorts of conflicts with the META-INF files.
> 🔥 Remove Logback

- features/task/src/commonMain/kotlin/com/escodro/task/presentation/list/TaskList.kt
- gradle/libs.versions.toml
Upgraded the Compose Compiler version from alpha to beta for improved stability and features. This change aligns with the latest updates in the Compose ecosystem.
> ✨ Update Compose Compiler to 1.8.0-beta01

- gradle/wrapper/gradle-wrapper.properties
Update Gradle to the latest version
> ⬆️ Update gradle-wrapper.properties

- gradle/libs.versions.toml
Updated the target SDK version to align with the latest Google Play requirements.
> ✨ Update Android SDK target version to 35
