igorescodro/alkaa

- app/src/androidTest/java/com/escodro/alkaa/framework/Events.kt
- app/src/androidTest/java/com/escodro/alkaa/ui/TaskFlowTest.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/TaskDetailProvider.kt
- app/src/main/java/com/escodro/alkaa/ui/task/detail/alarm/TaskAlarmViewModel.kt
Once the LiveData was not being cleared after each interaction, if the new value was "null" for category (which happens when creating a new one every time), the LiveData would load the previous one. This impacts only the UI, the data remains with no category.
> Fix UI error where category is not cleared for the next one

- app/src/main/java/com/escodro/alkaa/di/Modules.kt
- app/src/main/java/com/escodro/alkaa/ui/main/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListContract.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListFragment.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListState.kt
- app/src/main/java/com/escodro/alkaa/ui/task/list/TaskListViewModel.kt
Task List state was being controlled by hardcoded constants that
were passed from Contract until reach the Activity.
The code is now refactored to use sealed classes to share the current
state between the Activity and the logic part. The contract methods
that were overload are now separated for each action.
> :recycle: Remove hardcoded constants to control Task List state

- app/src/main/java/com/escodro/alkaa/ui/main/MainActivity.kt
[root-cause] Based on Google Issue Tracker 134627094, it is not
recommended to use ActionBarDrawerToggle when using Navigation
Jetpack.
[solution] Replace ActionBarDrawerToggle by SimpleDrawerListener.
Also, removed the code that reloads the Category when the drawer was
opened now that Alkaa is using Flowable to load all updatable data
> :bug: Wrong back button when opening Task from Notification

- data/local/src/main/java/com/escodro/local/provider/DatabaseProvider.kt
[root-cause] Once all the DAO methods are now observables, it is
needed to call `subscribe` when using it
[solution] Call `subscribe` on Database Provider
> :bug: Default categories are not being added

- app/src/androidTest/java/com/escodro/alkaa/ui/TaskCategoryTest.kt
- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/usecase/taskwithcategory/LoadTasksByCategory.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListFragment.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListViewModel.kt
[root-cause] If the list is showing the tasks under category, the user
removes the category and returns to the screen, the app crashes trying
to insert a task with an invalid foreign key.
[solution] When opening the list by category, first of all, checks if
the category is in the database. If not, the list is reloaded showing
all the uncompleted tasks.
> Fix app crash when adding a task in a deleted category

- buildSrc/src/main/java/Dependencies.kt
- features/category/src/main/java/com/escodro/category/presentation/detail/CategoryDetailFragment.kt
- libraries/navigation/src/main/res/navigation/nav_graph_category.xml
[root-cause] After Google update on Jetpack Navigation, it is not
possible to pass null value via Safe Args. That's on you, Google. :(
[solution] Set the default value as "0L" and handle it as adding a new
category
> :bug: Update Navigation crash

- features/tracker/build.gradle
[root-cause] When running Instrumented Tests, the issue to link Android
resources related to WorkManager failed.
[solution] Adding missing dependencies from Dynamic Module to
Application module to correctly link all resources
> Fix processDebugAndroidTestResources issue

- app/src/main/res/values-night/themes.xml
[root-cause] The status bar icons (clock, battery etc) is black when
using Dark Theme. This way it is not possible to see them.
[solution] Create a `values-night` theme and set `windowLightStatusBar`
to false on it
Closes #86
> Status bar icons not visible on Dark Theme

- features/category/src/main/java/com/escodro/category/presentation/list/CategoryListFragment.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListFragment.kt
- libraries/core/src/main/java/com/escodro/core/extension/DialogExtensions.kt
- libraries/splitInstall/src/main/java/com/escodro/splitinstall/SplitInstall.kt
[root-cause] The confirmation buttons on dialogs are off styles.
[solution] Update import from `android` to `androidx`
Closes #87
> Dialog button is weird on latest release

- config/dependencies/dynamic_dependencies.gradle
- features/tracker/build.gradle
The dependencies were duplicated on the Tracker Gradle and the base
dynamic feature Gradle. Code updated to only add on the base one.
Also moved the test dependency to base as well.
> Remove duplicate code

- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/interactor/AlarmInteractor.kt
- data/domain/src/main/java/com/escodro/domain/usecase/alarm/CancelAlarm.kt
- data/domain/src/main/java/com/escodro/domain/usecase/alarm/ScheduleAlarm.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/CancelAlarmTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/ScheduleAlarmTest.kt
- features/alarm/src/main/java/com/escodro/alarm/di/AlarmModule.kt
- features/alarm/src/main/java/com/escodro/alarm/interactor/AlarmInteractorImpl.kt
- features/alarm/src/main/java/com/escodro/alarm/notification/TaskNotificationScheduler.kt
- features/task/build.gradle
- features/task/src/main/java/com/escodro/task/di/TaskModule.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/TaskAlarmViewModel.kt
The relation between Alarm and Task were direct. Update the code to create a Use Case for Alarm usage and communicate with Task through interactor, inverting the dependency flow between than to Domain.
> Refactor communication between Alarm and Task

- data/domain/src/main/java/com/escodro/domain/di/DomainModule.kt
- data/domain/src/main/java/com/escodro/domain/usecase/alarm/RescheduleFutureAlarms.kt
- data/domain/src/test/java/com/escodro/domain/usecase/alarm/RescheduleFutureAlarmsTest.kt
[root-cause] The use case was only trying to schedule the alarm for the
time the task was missed. Alarms in the past are not scheduled and is
not the expected behavior.
[solution] Add a separate logic to handle the missed repeating alarms.
Now if the alarm was a missed repeating, it calls the use case to ensure
that this alarm will be scheduled in the future.
> Missed repeating tasks are not working after reboot

- features/task/src/main/java/com/escodro/task/presentation/list/TaskAddItem.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskItem.kt
[root-cause] Every new interaction that updates the list makes it blink
and refresh all the items.
[solution] When updating the code to use Groupie, I forgot to implement
the "getId()" and "equals()" functions, which makes the diff between the
items. As soon as it is implemented, it starts working properly.
> :bug: List is always refreshing all items when updated

- buildSrc/src/main/java/Dependencies.kt
Android Gradle Plugin updated to 7.0.0-alpha06 to match latest Android
Studio version.
> ⬆️ Upgrade AGP to latest version

- features/search/src/main/java/com/escodro/search/presentation/Search.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailActions.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/TaskAlarmViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/category/TaskCategoryViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetailViewModel.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListViewModel.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskAlarmViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskCategoryViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskDetailViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/LoadUncompletedTasksFake.kt
- features/task/src/test/java/com/escodro/task/presentation/list/TaskListViewModelTest.kt
After a great discussion in kotlinlang Slack, some refactor were made to update the _hot flows_ to _cold flows_, giving more lifecycle control and avoiding multiple recompositions in different screens.
Special thanks to @adamp.
> Refactor after Composable discussions.

- features/search/src/main/java/com/escodro/search/presentation/Search.kt
[root-cause] Instead of setting the height to a fix value, the size was
set.
[solution] Set only the height to fix size and add width to fill parent.
> 🐞 Search item title is now showing the complete text

- data/domain/src/main/java/com/escodro/domain/repository/CategoryRepository.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/LoadAllCategories.kt
- data/domain/src/main/java/com/escodro/domain/usecase/category/implementation/LoadAllCategoriesImpl.kt
- data/domain/src/test/java/com/escodro/domain/usecase/category/AddCategoryTest.kt
- data/domain/src/test/java/com/escodro/domain/usecase/fake/CategoryRepositoryFake.kt
- data/local/src/main/java/com/escodro/local/dao/CategoryDao.kt
- data/local/src/main/java/com/escodro/local/datasource/CategoryLocalDataSource.kt
- data/repository/src/main/java/com/escodro/repository/CategoryRepositoryImpl.kt
- data/repository/src/main/java/com/escodro/repository/datasource/CategoryDataSource.kt
- features/task/src/main/java/com/escodro/task/presentation/category/TaskCategoryViewModel.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/LoadAllCategoriesFake.kt
[root-cause] The default categories are added to the database when the
user first open the app. Due to some database write delay, the screen
finished loading before that data is available to fetch.
[solution] Update the category fetch to return a Flow instead of a
suspend function of a list. This way, when the data is updated and ready
to be used, the Flow will emit an update to the UI recompose.
> 🐞 Default categories does not shown up in first usage

- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/HomeActions.kt
- features/preference/src/androidTest/java/com/escodro/preference/AboutTest.kt
- features/preference/src/androidTest/java/com/escodro/preference/PreferenceSectionTest.kt
- features/preference/src/main/java/com/escodro/preference/presentation/About.kt
- features/preference/src/main/java/com/escodro/preference/presentation/Preference.kt
- features/search/src/androidTest/java/com/escodro/search/SearchSectionTest.kt
- features/search/src/main/java/com/escodro/search/presentation/Search.kt
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/CategorySelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/TaskItemTest.kt
- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
- features/task/src/main/java/com/escodro/task/presentation/category/CategorySelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/TaskDetailActions.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
- features/task/src/main/java/com/escodro/task/presentation/detail/main/TaskDetail.kt
- features/task/src/main/java/com/escodro/task/presentation/list/CategoryStateHandler.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskListComponents.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskStateHandler.kt
- libraries/theme/src/main/java/com/escodro/theme/components/AlkaaComponents.kt
The official documentation states that the lambdas should be renamed in
present rather than in past tense, "as the event doesn't mean the state
has already changed, but rather that the composable is requesting that
the event handler change it."
> ♻️ Rename lambdas for the present-tense

- buildSrc/src/main/java/Dependencies.kt
Compose updated to Beta-03 and all Compose-related libraries upgraded
to its respective versions.
> ⬆️ Upgrade Compose to latest Beta

- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- features/task/src/androidTest/java/com/escodro/task/espresso/Events.kt
- libraries/test/build.gradle
- libraries/test/src/main/java/com/escodro/test/DisableAnimationsRule.kt
Add the Test Rule to disable animations when using components from
Android View System.
> ✅ Remove flakiness from AlarmSelectionTest

- buildSrc/src/main/java/Dependencies.kt
- gradle/wrapper/gradle-wrapper.properties
Android Gradle Plugin updated to 7.0.0-alpha14 to match latest Android
Studio version
> ⬆️ Upgrade Android Gradle Plugin

- buildSrc/src/main/java/Dependencies.kt
- config/dependencies/compose_dependencies.gradle
Compose updated from 1.0.0-alpha04 to alpha05.
> ⬆️ Upgrade Compose dependencies to latest version

- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
[root-cause] The onClick function in the Composable was only updating
the UI and not calling the callback hoisted to in fact update the
ViewModel.
[solution] Call the callback to notify the ViewModel and made the correct
updates
> 🐞 Alarm is not removed when clicking in the X button

- app/src/main/java/com/escodro/alkaa/core/Handlers.kt
- app/src/main/java/com/escodro/alkaa/presentation/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
In the previous implementation, if the BottomSheet was opened and the
user presses the back button, the app was closed. Now, if the
BottomSheet is opened, it will first close it and only then it will
close the application.
> ✨ Close BottomSheet when back is pressed

- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
[root-cause] The states representing the add task BottomSheet data were
not supporting orientation changes.
[solution] Replace common `remember` with `rememberSaveable`
> 🐞 Add Task BottomSheet loses data when rotated

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
[root-cause] When the device is in landscape with the BottomSheet opened
and the user rotates the device, it crashes with the following message:
java.lang.IllegalArgumentException: The initial value must have an
associated anchor.
[solution] Although we don't have an official solution for this issue
(see linked IssueTracker), I was able to find a workaround to avoid
this bug.
First of all, I used a `BoxWithConstraints` to know exactly when the
device is in landscape mode. When in landscape, the
`ModalBottomSheetLayout` has a weird behavior related to its height: it
allows only `fillMaxHeight` or values lower the half screen. Since I
don't want the BottomSheet to be fullscreen, I updated the code with
using fractions of the screen. When the app is in portrait, it uses
one value and when in …
> 🐞 BottomSheet crashes when rotating from landscape

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/category/src/main/java/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/task/src/main/java/com/escodro/task/presentation/add/AddTask.kt
This reverts commit 5bf2b6ce
In the Compose 1.0.0-RC01, the BottomSheet issue was kinda fixed.
When rotating the screen with a BottomSheet opened, it simply
closes. This solves the crash issue and I hope that Google will
improve this behavior in the future.
> Revert "🐞 BottomSheet crashes when rotating from landscape (#193)"

- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
In the earlier versions of Jetpack Compose, the BottomSheet background
would consume the click button and dismiss it. Then I added a empty
click event to ignore this behavior. Now in latest versions this issue
was fixed and the workaround can be now removed.
> 🔥 Remove BottomSheet clickable workaround

- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- features/task/src/androidTest/java/com/escodro/task/espresso/Events.kt
Once JCenter will be turned off in 2022 and all the dependencies used in
Alkaa were already ported, it was replaced by Maven Central instead.
> 🗑️ Remove JCenter in favor of MavenCentral

- app/build.gradle
- config/dependencies/dynamic_dependencies.gradle
- data/local/build.gradle
- data/repository/build.gradle
- features/alarm/build.gradle
- features/category/build.gradle
- features/preference/build.gradle
- features/search/build.gradle
- features/task/build.gradle
- features/tracker/build.gradle
- libraries/splitInstall/build.gradle
- libraries/test/build.gradle
- settings.gradle
Enable the new feature on Gradle 7.0 and update all the projects
references form hardcoded to type-safe calls.
> ⬆️ Enable Gradle's Type-safe Project Accessors

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/model/HomeSection.kt
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- buildSrc/src/main/java/GradlePlugin.kt
- buildSrc/src/main/java/gradle/quality.gradle.kts
- buildSrc/src/main/java/quality/detekt.gradle.kts
- buildSrc/src/main/java/quality/ktlint.gradle.kts
Well, you again... This time I found out that the task "detekt" was
working but now being executed in the "check" task. Now it's working...
Also, I saw that the quality plugins were not called in the :app module.
Ouch! Updated and the issues were fixed.
> 🚨 Fix Quality Plugin

- app/src/main/java/com/escodro/alkaa/di/AppModule.kt
- data/local/src/main/java/com/escodro/local/di/LocalModule.kt
- data/local/src/main/java/com/escodro/local/provider/DaoProvider.kt
- data/local/src/main/java/com/escodro/local/provider/DatabaseProvider.kt
- features/alarm/src/main/java/com/escodro/alarm/TaskReceiver.kt
Instead of using GlobalScope, now Alkaa was updated to use an app based
CoroutineScope for more flexibility and control.
> ♻️ Remove GlobalScope references from the codebase

- app/proguard-rules.pro
- features/category-api/proguard-rules.pro
- features/category/proguard-rules.pro
- features/task/proguard-rules.pro
[issue] Even after adding the rules for Parcelable on ProGuard Rules,
the BadParcelableException was reported in the Google Play. It seems
that it may be related to the Parcelable Creator.
[solution] Add the `*` for keep the names for any Parcelable reference
in the code, even the static CREATOR
>  🐞 Fix BadParcelableException

- features/search/src/test/java/com/escodro/search/presentation/SearchViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/detail/TaskDetailViewModelTest.kt
Removing the `advanceUntilIdle` and `runCurrent` from all tests since the new `runTest` API already automatically waits for all known coroutines. Info found the great article from @zsmb13, thanks!
> ✅ Remove unused Coroutines Test APIs

- app/src/androidTest/java/com/escodro/alkaa/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- app/src/androidTest/java/com/escodro/alkaa/NotificationFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/PreferenceFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/SearchFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskListFlowTest.kt
- features/task/src/androidTest/java/com/escodro/task/AlarmPermissionFlowTest.kt
- features/task/src/androidTest/java/com/escodro/task/AlarmSelectionTest.kt
- libraries/test/build.gradle.kts
- libraries/test/src/main/java/com/escodro/test/FlakyTest.kt
Unfortunately, the Instrumented Tests are failing a lot in the CI due to the Compose + Gradle Managed Devices usage. Since I'm not able to reproduce any of those failures locally, the silver tape solution now is basically creating a rule to allow them to run again. The extra setup is required due to how Compose default rules create the Activities.
By having a single rule and just applying it to the Tests, it's possible to have a single source of truth. Then we can just remove it in the future when Managed Devices are more stable.
For more info, please take a look:
https://proandroiddev.com/managing-flaky-tests-in-jetpack-compose-89c598590068
> ✅ Allow some test class to be flaky

- .github/workflows/android_tests.yml
Android Gradle Managed Devices are very unstable recently, basically failing every single job due to some unknown system crash. I believe that this started to happen after the API 33 upgrade, but we need to wait and see.
The solution, for now, is trying to revert to ReactiveCircus/android-emulator-runner.
> 👷 Replace Gradle Managed Devices for ReactiveCircus Plugin

- .github/workflows/release.yml
Script updated to automatically release on Google Play and the GitHub release use the Git Tag name instead
> 👷 Update Release GitHub Actions

- .github/workflows/android_tests.yml
- .github/workflows/build.yml
Today the trigger is only "on push", which is not good when external contributors try to submit PRs. Updating to also trigger "on pull request" and only when pushing to main. This configuration is based on the Accompanist one.
> 👷‍ Executes CI on Pull Request

- .github/workflows/release.yml
Oops... This information is now missing when not triggered by refs/tags
> 👷 Update the GitHub actions to get the tag name for the release

- app/src/main/java/com/escodro/alkaa/di/AppModule.kt
- data/local/src/main/java/com/escodro/local/di/LocalModule.kt
- features/alarm/build.gradle.kts
- features/alarm/src/main/java/com/escodro/alarm/TaskReceiver.kt
- features/category/src/main/java/com/escodro/category/di/CategoryModule.kt
- features/glance/build.gradle.kts
- features/glance/src/main/java/com/escodro/glance/presentation/TaskListGlanceWidget.kt
While creating the new ApplicationScope, I didn't realized that a Scope was already in place. That was confusing, especially because both have the same goal. In order to make it better, one was removed and the one with qualifier is kept.
> ♻️ Remove duplicated CoroutineScope

- .github/workflows/android_tests_aer.yml
- .github/workflows/android_tests_gmd.yml
- app/build.gradle.kts
I really like the Gradle Managed Devices, however, it seems more unreliable than the Android Emulator Runner by ReactiveCircus. For now, instead of going back and forth between them, both will run with similar configuration.
> 💚 Duplicate the scripts for running instrumented tests

- features/glance/src/main/java/com/escodro/glance/data/TaskListStateDefinition.kt
- features/glance/src/main/java/com/escodro/glance/presentation/TaskListGlanceWidget.kt
After moving from `List` to `ImmutableList` the Glance stopped working. It seems that serialization and/or encoding does not work very well with this library. For now, the Serializer was reverted to `List` and the conversion to ImmutableList will happen in the UI before rendering it.
I just found the following Exception on the stacktrace:
```
java.util.concurrent.ExecutionException: kotlinx.serialization.SerializationException: Class 'SmallPersistentVector' is not registered for polymorphic serialization in the scope of 'ImmutableList'.
Mark the base class as 'sealed' or register the serializer explicitly.
at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
at …
```
> 🐞 Fix Glance not working issue

- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
In the new Snackbar API on Material You, if it does contain an `actionLabel` such as "Undo", the duration is set to "Indefinite". This was causing the Snackbar to never disappear. The API call was updated explicit passing the argument to show during a short period of time.
> 🐞 Fix Snackbar never disappearing issue

- features/glance/src/main/java/com/escodro/glance/presentation/TaskListGlanceWidget.kt
In the past, we migrated some of the ViewModelScopes to ApplicationScope to ensure that the execution would run regardless of the view state. However, in a very specific flow I was cancelling this Scope.
This cancellation was happening when the Glance widget was removed from the home screen. When this cancellation was called, than no new execution was made in that scope.
The quick fix for now is simply removing the cancellation, however I will investigate how to avoid this issue in the near feature by creating some kind of protection to its cancellation.
> 🐞 Fix issue when sometimes the app does not add or update tasks

- app/build.gradle.kts
- app/src/androidTest/java/com/escodro/alkaa/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/HomeScreenTest.kt
- app/src/androidTest/java/com/escodro/alkaa/NotificationFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/PreferenceFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/SearchFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskListFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/util/WindowSizeClassFake.kt
- app/src/main/java/com/escodro/alkaa/navigation/NavGraph.kt
- app/src/main/java/com/escodro/alkaa/presentation/AlkaaAppState.kt
- app/src/main/java/com/escodro/alkaa/presentation/MainActivity.kt
- app/src/main/java/com/escodro/alkaa/presentation/home/Home.kt
- features/task/src/main/java/com/escodro/task/presentation/list/TaskList.kt
- gradle/libs.versions.toml
After some initial efforts on #225, now it's time for Alkaa to properly support different form factors. The first step is implementing a [NavigationRail](https://m3.material.io/components/navigation-rail/overview) to better accommodate the navigation icons on the screen.
The next PRs improve the experience by using multiple panes and better using the empty space on the screen.
| ![Screenshot_1674835538](https://user-images.githubusercontent.com/2267495/215134161-58b12c2d-0bbf-4051-a9f0-6272b7e81e30.png) | ![Screenshot_1674835520](https://user-images.githubusercontent.com/2267495/215134155-dfd476fc-8e1a-4cd2-a68f-65fac03f8db3.png)| ![Screenshot_1674835533](https://user-images.githubusercontent.com/2267495/215134158-59fbe3d1-34af-4ab2-b92d-16a9089dda47.png)  | …
> 🎨 Add Navigation Rail to Home Composable

- features/task/src/main/java/com/escodro/task/presentation/detail/alarm/PermissionDialogs.kt
Specify the application package name to directly Invoke "Alarms & reminders" management specific to the app.
Described on the [ACTION_REQUEST_SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_SCHEDULE_EXACT_ALARM) permission page.
> Invoke app specific "Alarms & reminders" settings

- app/build.gradle.kts
- gradle/libs.versions.toml
- libraries/test/build.gradle.kts
- plugins/src/main/java/com.escodro.android-compose.gradle.kts
- plugins/src/main/java/extension/VersionCatalogExtensions.kt
The Compose Bill Of Materials dependency was added to make it easier to update and match different Compose versions. Kotlin and KSP were also updated to match latest Compose.
> ➕ Add Compose BOM dependency

- app/src/androidTest/java/com/escodro/alkaa/CategoryFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/NotificationFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/SearchFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskFlowTest.kt
- app/src/androidTest/java/com/escodro/alkaa/TaskListFlowTest.kt
- data/local/src/test/java/com/escodro/local/datasource/SearchLocalDataSourceTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/CancelAlarmTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/RescheduleFutureAlarmsTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/ScheduleAlarmTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/ScheduleNextAlarmTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/ShowAlarmTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/SnoozeAlarmTest.kt
- domain/src/test/java/com/escodro/domain/usecase/alarm/UpdateTaskAsRepeatingTest.kt
- domain/src/test/java/com/escodro/domain/usecase/category/AddCategoryTest.kt
- domain/src/test/java/com/escodro/domain/usecase/category/DeleteCategoryTest.kt
- domain/src/test/java/com/escodro/domain/usecase/category/UpdateCategoryTest.kt
- domain/src/test/java/com/escodro/domain/usecase/preferences/AppThemeTest.kt
- domain/src/test/java/com/escodro/domain/usecase/search/SearchTasksTest.kt
- domain/src/test/java/com/escodro/domain/usecase/task/AddTaskTest.kt
- domain/src/test/java/com/escodro/domain/usecase/task/CompleteTaskTest.kt
- domain/src/test/java/com/escodro/domain/usecase/task/DeleteTaskTest.kt
- domain/src/test/java/com/escodro/domain/usecase/task/UpdateTaskTest.kt
- domain/src/test/java/com/escodro/domain/usecase/taskwithcategory/LoadTasksTest.kt
- domain/src/test/java/com/escodro/domain/usecase/tracker/LoadCompletedTasksByPeriodTest.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/CoroutinesDebouncerFake.kt
- gradle/libs.versions.toml
KotlinX Coroutines updated and deprecated annotations removed
> Update Coroutines to 1.7.1 

- app/build.gradle.kts
Actually, the precious change to allow external PRs broke other stuff (as always). A new function was created to gracefully handle the properties.
> 👷 Update the CI again

- gradle.properties
One more of the configs that was added but not sure why. By removing it, the cache and build speed will be faster, based on the warnings. So far, no issues with the iOS app.
> 🔧 Update `gradle.properties` to allow native cache

- .gitignore
- app/build.gradle.kts
- plugins/src/main/java/quality/ktlint.gradle.kts
A silly mistake while migrating to Gradle 8 and `buildDir` was deprecated. Turns out that `layout.buildDirectory` is not a simple String replacement with the new path.
https://docs.gradle.org/current/userguide/upgrading_version_8.html#project_builddir
> 🔧 Fix check reports issues

- build.gradle.kts
- features/home/build.gradle.kts
- features/home/src/commonMain/kotlin/com/escodro/home/presentation/Home.kt
- features/home/src/commonMain/kotlin/com/escodro/home/presentation/HomeActions.kt
- features/home/src/commonMain/kotlin/com/escodro/home/presentation/HomeSection.kt
- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
- ios-app/alkaa/Info.plist
- resources/build.gradle.kts
- resources/src/commonMain/resources/MR/base/strings.xml
- resources/src/commonMain/resources/MR/pt-br/strings.xml
- settings.gradle.kts
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
A new module (`:features:home`) was created to hold the home feature from Android's `:app` module. This module will be responsible for the main Scaffold and basic navigation between tabs.
In the previous structure, this code was inside Android's `:app` but in order to make it multiplatform, we need a dedicated module. We could put the logic on `shared`, but my goal for that module is just to be an "umbrella" with a small setup.
Also, Moko Resources was added to handle the resources on all platforms.
> 🏠 Implement the Home UI-feature

- app/build.gradle.kts
- app/src/main/java/com/escodro/alkaa/MainActivity.kt
- features/glance/build.gradle.kts
- features/glance/src/main/java/com/escodro/glance/presentation/TaskListGlanceWidget.kt
- libraries/navigation/build.gradle.kts
- libraries/navigation/src/androidMain/kotlin/com/escodro/navigation/AndroidDestinations.kt
- libraries/navigation/src/commonMain/kotlin/com/escodro/navigation/NavigationAction.kt
- shared/src/androidMain/kotlin/com/escodro/shared/Main.android.kt
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
- shared/src/commonMain/kotlin/com/escodro/shared/navigation/AlkaaNavGraph.kt
Voyager does not have support for deep links or navigation from outside of the app at this moment. Because of that, a very simple structure was created to allow navigation through notifications and widgets using deep links. For now, it only applies to the Android platform.
The idea is to have a single deep link redirecting to the MainActivity and send a single extra, which is a sealed interface representing the destination and the parameters needed. The activity gets this information from the Intent and passes it to the navigation graph. After that, all the execution is multiplatform.
The navigation graph consumes the action and sends it to the appropriate screen (for now, only Task Details). If no information is provided, it stays on the home screen and no extra steps are taken.
For a …
> ✨ Re-enable the ability of navigating using deep links

- gradle/libs.versions.toml
- plugins/src/main/java/extension/CommonExtension.kt
Update the AGP to the latest version and update the `CommonExtension` extension function adding the new wildcard for the new param in AGP 8.3.x.
Closes #635
> ⬆️ Upgrade AGP to 8.3.2

- ios-app/alkaa/Info.plist
Adding information on why SPrivacyAccessedAPICategoryFileTimestamp is used by our app.
> 🔧 Update Info.plist to be in compliance with Apple request

- domain/src/commonMain/kotlin/com/escodro/domain/di/DomainModule.kt
- domain/src/commonMain/kotlin/com/escodro/domain/interactor/AlarmInteractor.kt
- domain/src/commonMain/kotlin/com/escodro/domain/usecase/task/implementation/UpdateTaskTitleImpl.kt
- domain/src/commonTest/kotlin/com/escodro/domain/usecase/fake/AlarmInteractorFake.kt
- domain/src/commonTest/kotlin/com/escodro/domain/usecase/task/UpdateTaskTest.kt
- features/alarm/src/androidMain/kotlin/com/escodro/alarm/notification/AndroidNotificationScheduler.kt
- features/alarm/src/commonMain/kotlin/com/escodro/alarm/interactor/AlarmInteractorImpl.kt
- features/alarm/src/commonMain/kotlin/com/escodro/alarm/notification/NotificationScheduler.kt
- features/alarm/src/iosMain/kotlin/com/escodro/alarm/notification/IosNotificationScheduler.kt
In iOS, the notification is scheduled with the task data when it is created. This means that if the title changes over time, the notification would show the outdated title when the notification is launched.
In this proposed fix, the notification is updated when the title changes, providing the latest info to the interactor.
> 🐞 Fix bug where the notification does not have the updated title in iOS

- build.gradle.kts
- gradle.properties
- ios-app/alkaa.xcodeproj/project.pbxproj
- ios-app/alkaa.xcodeproj/xcshareddata/xcschemes/alkaa.xcscheme
Kotlin Multiplatform has a lot of experimental and on-going work under the hood to improve the codebase. Let's ignore some repetitive warnings to make sure we are paying attention to the important ones!
> 👷 Reduce build warning

- ios-app/ci_scripts/ci_post_clone.sh
Update the JDK match the one in Gradle 8.7, allowing the Xcode Cloud to build the project.
> 👷 Update ci_post_clone.sh

- features/task/src/commonMain/kotlin/com/escodro/task/di/TaskModule.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/add/AddTaskViewModel.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/add/TaskBottomSheet.kt
- features/task/src/test/java/com/escodro/task/presentation/add/AddTaskViewModelTest.kt
- features/task/src/test/java/com/escodro/task/presentation/fake/AddTaskFake.kt
This is a quality of life feature to quickly add alarms while the task is being created. This creates a better UX and allow users to use Alkaa as a quick reminder without going to an additional screen.
> ✨ Add Alarm Selection in the Add Task Bottom Sheet

- features/task/src/commonMain/kotlin/com/escodro/task/presentation/add/TaskBottomSheet.kt
- gradle/libs.versions.toml
- ios-app/alkaa.xcodeproj/project.pbxproj
A recent change to add the alarm option in the Bottom Sheet broke the background color. In removed the manual background color relying on that the `MaterialTheme` would work but didn't test it properly.
> 🥡 Small fix for Bottom Sheet

- .github/workflows/build.yml
- config/filters/detekt.yml
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/list/TaskList.kt
- gradle/libs.versions.toml
- libraries/splitInstall/src/main/java/com/escodro/splitinstall/SplitInstall.kt
- plugins/src/main/java/extension/VersionCatalogLibraries.kt
- plugins/src/main/java/quality/detekt.gradle.kts
- plugins/src/main/java/quality/ktlint.gradle.kts
- shared/src/androidMain/kotlin/com/escodro/shared/Main.android.kt
- shared/src/commonMain/kotlin/com/escodro/shared/AlkaaMultiplatformApp.kt
- shared/src/commonMain/kotlin/com/escodro/shared/navigation/AlkaaNavGraph.kt
Ever since Twitter killed the Android Team, the ComposeRules project was deprecated and amazing devs from the community forked and support it. This change moves to the project and fixes the new lint rules
> 📐 Migrate Compose Rules to the new project 

- gradle/libs.versions.toml
Based on Google Play Console and Lint warnings, the library was migrated from Play Core to a specific one with proper Android 14 support.
https://developer.android.com/guide/playcore#playcore-migration
> ▶️ Migrate Play Core library

- app/build.gradle.kts
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/detail/alarm/AlarmSelection.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/detail/alarm/DateTimePicker.kt
- plugins/src/main/java/com.escodro.kotlin-parcelable.gradle.kts
- plugins/src/main/java/com.escodro.kotlin-quality.gradle.kts
- plugins/src/main/java/extension/CommonExtension.kt
- plugins/src/main/java/extension/KmpExtensions.kt
- plugins/src/main/java/quality/ktlint.gradle.kts
- shared/build.gradle.kts
This commit fixes #769
* `DateTimePicker` now has a field for its initial value
* The alarm will load the existing value if it exists
> Add initial value to `DateTimePicker` and load existing value 

- build.gradle.kts
- data/datastore/src/commonMain/kotlin/com/escodro/datastore/DataStore.kt
- gradle.properties
- gradle/libs.versions.toml
Removing the library since it generates some conflicts with other libraries, and it's only used in Alkaa to make DataStore.kt a singleton.
For now, the code was updated to use the same sync functions from the stdlib.
> ☢️ Remove AtomicFU

- ios-app/alkaa/Info.plist
The iOS app was crashing after a few seconds being open because of the missing Info.plist property.
> 🦟 Fix iOS crash related to CADisableMinimumFrameDurationOnPhone

- features/preference/src/commonMain/kotlin/com/escodro/preference/presentation/OpenSource.kt
Occasionally, the AboutLibraries breaks the app during Compose updates. This happens due to a `No static method FlowRow` error for the License Badges. To avoid this constant issue, a simple workaround is to remove the component from the list.
Source: https://github.com/mikepenz/AboutLibraries/issues/1033
> 🪪 Disable License Badges for AboutLibraries

- features/category/src/commonMain/kotlin/com/escodro/category/presentation/bottomsheet/CategoryBottomSheet.kt
- features/task/src/commonMain/kotlin/com/escodro/task/presentation/add/TaskBottomSheet.kt
- settings.gradle.kts
I read the [official documentation](https://developer.android.com/develop/ui/compose/components/bottom-sheets?hl=en) and I noticed that the examples are not using `.show()`. My speculation is that the animation is called by default, and the original code duplicated the animation, leading to the behaviour shown in the demo.
Here is a demo of this PR:
https://github.com/user-attachments/assets/c659918e-ec35-48c8-b436-1c7882d5d124
Fixes #864.
> Fix: improve bottom sheet animation

- features/navigation-api/src/commonMain/kotlin/com/escodro/navigationapi/destination/HomeDestination.kt
- libraries/parcelable/build.gradle.kts
- libraries/parcelable/src/commonMain/kotlin/com/escodro/parcelable/CommonParcelable.kt
- libraries/parcelable/src/desktopMain/kotlin/com/escodro/parcelable/CommonParcelable.desktop.kt
- libraries/parcelable/src/iosMain/kotlin/com/escodro/parcelable/CommonParcelable.ios.kt
- libraries/parcelable/src/main/java/com/escodro/parcelable/CommonParcelable.android.kt
The `title` and `icon` members of the `HomeDestination` data objects are now annotated with `@CommonIgnoredOnParcel`. This will suppress the build warning related to these properties.
> 🧱 Add @CommonIgnoredOnParcel to HomeDestination members

- build.gradle.kts
- gradle/libs.versions.toml
The dependency-analysis plugin and its references were removed from `build.gradle.kts` and `libs.versions.toml`, as it is no longer required.
> 🍂 Remove dependency-analysis plugin

- gradle/libs.versions.toml
Bumped the `android_sdk_compile` version from 35 to 36 in the Gradle configuration.
> 🛠️ Update Android compile SDK version to 36
